#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

RESTRICTED_BRANCHES="develop"
BRANCH_REGEX='^[A-Z]+-[0-9]+$'

if [[ " $RESTRICTED_BRANCHES " =~ " $BRANCH_NAME " ]]; then
    echo "Commit rejected: cannot commit to restricted branches (${RESTRICTED_BRANCHES// /, })"
    echo "Create a feature branch and submit a PR"
    exit 1
elif ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    echo "Commit rejected: branch name '$BRANCH_NAME' does not match required format"
    echo "$BRANCH_REGEX"
    exit 1
else
    echo "Branch name $BRANCH_NAME is valid"
fi
